export default [
  {
    id: 0,
    title: "Rain Outside Your Window",
    src: "./musics/rain-outside-your-window.mp3",
    artist: "OYStudio",
    style: "classical",
    time: "2:10",
  },
  {
    id: 1,
    title: "Rising Sun",
    src: "./musics/rising-sun.mp3",
    artist: "OYStudio",
    style: "classical",
    time: "2:43",
  },
  {
    id: 2,
    title: "Endless Snowfall",
    src: "./musics/endless-snowfall.mp3",
    artist: "Eugene Barduja",
    style: "classical",
    time: "2:08",
  },
  {
    id: 3,
    title: "Beethoven Piano Sonata No 14",
    src: "./musics/beethoven-piano-sonata-no-14.mp3",
    artist: "OYStudio",
    style: "classical",
    time: "6:54",
  },
  {
    id: 4,
    title: "Corporate Harmonics",
    src: "./musics/corporate-harmonics.mp3",
    artist: "Motion Array",
    style: "rock",
    time: "1:49",
  },
  {
    id: 5,
    title: "Pop Rock Music Kit",
    src: "./musics/demo-song.mp3",
    artist: "Motion Array",
    style: "rock",
    time: "1:27",
  },
  {
    id: 6,
    title: "In The Dark",
    src: "./musics/in-the-dark.mp3",
    artist: " Lemon Music Studio",
    style: "rock",
    time: "1:41",
  },
  {
    id: 7,
    title: "Back In Time",
    src: "./musics/back-in-time.mp3",
    artist: "Eugene Barduja",
    style: "eletronic",
    time: "2:11",
  },
  {
    id: 8,
    title: "Acid Network",
    src: "./musics/acid-network.mp3",
    artist: "Motion Array",
    style: "eletronic",
    time: "1:35",
  },
  {
    id: 9,
    title: "Ready To Take Off",
    src: "./musics/ready-to-take-off.mp3",
    artist: "GvidonAudio",
    style: "eletronic",
    time: "2:13",
  },
];
